In [35]:
import psycopg2
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine
import json
import pyodbc

with open('user_address.json') as data_file:    
    d = json.load(data_file)
    
conn=psycopg2.connect(
        host = "localhost",
        user = "postgres",
        password = "secret123",
        database = "shipping_orders",
        port = "5432")

cur=conn.cursor() 

def create_table():
   
   cur.execute(
        """CREATE TABLE IF NOT EXISTS user_address_master (first_name varchar(256),
                                                                    last_name varchar(256),
                                                                    email varchar(256),
                                                                    address varchar(256),
                                                                    created_at timestamp)"""
    )
   conn.commit() 
   conn.close()

In [2]:
create_table()

In [14]:
header_list = ["first name", "last name", "email", "address", "created at"]
df=pd.read_csv('dataset-medium.csv', names=header_list)

In [15]:
df

,first name,last name,email,address,created at
0,Galih,Kuswandari,iriyanti@yahoo.com,"Jl. Raya Ujungberung No. 25Cirebon, Kalimantan...",2018-07-08T13:31:43.241000Z
1,Ikin,Haryanti,warta96@yahoo.com,"Gang Asia Afrika No. 5Cimahi, Jawa Barat 85755",2018-07-27T07:19:43.924000Z
2,Warta,Pudjiastuti,kemalfarida@perum.int,"Gg. Rajawali Timur No. 66Batam, NTB 77223",2018-03-19T20:19:02.226000Z
3,Rahmat,Prasetyo,tusada@hotmail.com,"Lr. Sukajadi No. 5Padangpanjang, Kalimantan Se...",2018-03-23T10:14:13.225000Z
4,Cindy,Yolanda,candrakantasantoso@cv.edu,"Lr. Kiaracondong No. 1Makassar, Sulbar 81715",2018-12-11T09:31:02.254000Z
...,...,...,...,...,...
299995,Yulia,Tampubolon,namagaulya@yahoo.com,"Gang Raya Ujungberung No. 128Bengkulu, Sulbar ...",2018-09-28T16:48:33.801000Z
299996,Hesti,Pangestu,prasetyoprasasta@hotmail.com,"Lr. Jamika No. 30Langsa, DI Yogyakarta 46837",2018-03-13T07:57:12.352000Z
299997,Ajeng,Nugroho,lukman09@ud.co.id,"Lorong Kebonjati No. 409Langsa, Gorontalo 58115",2018-06-04T20:25:34.680000Z
299998,Darman,Januar,jaswadi89@ud.edu,Gang Sukajadi No. 20Kota Administrasi Jakarta ...,2018-11-25T16:22:05.122000Z
299999,Cager,Hutagalung,karjasaptono@perum.my.id,"Lorong Dipatiukur No. 40Tanjungpinang, Kalbar ...",2018-03-01T19:43:53.902000Z

In [16]:
df.shape

(300000, 5)

In [17]:

import pandas as pd
 
# read DataFrame
data = pd.read_csv('dataset-medium.csv', names=header_list)
 
# no of csv files with row size
k = 10
size = 30000
 
for i in range(k):
    df = data[size*i:size*(i+1)]
    df.to_csv(f'data-part-{i+1}.csv', index=False)
 
df_1 = pd.read_csv("data-part-1.csv")
print(df_1)
 
df_2 = pd.read_csv("data-part-2.csv")
print(df_2)

      first name    last name                      email  \
0          Galih   Kuswandari         iriyanti@yahoo.com
1           Ikin     Haryanti          warta96@yahoo.com
2          Warta  Pudjiastuti      kemalfarida@perum.int
3         Rahmat     Prasetyo         tusada@hotmail.com
4          Cindy      Yolanda  candrakantasantoso@cv.edu
...          ...          ...                        ...
29995     Violet     Prasetyo          heryanto17@ud.gov
29996    Raharja    Saefullah            ggunawan@pd.mil
29997      Kenes      Fujiati  salsabilahabibi@gmail.com
29998      Dadap    Sihombing    pertiwialmira@cv.mil.id
29999   Estiawan     Andriani           fmayasari@ud.edu

                                                 address  \
0      Jl. Raya Ujungberung No. 25Cirebon, Kalimantan...
1         Gang Asia Afrika No. 5Cimahi, Jawa Barat 85755
2              Gg. Rajawali Timur No. 66Batam, NTB 77223
3      Lr. Sukajadi No. 5Padangpanjang, Kalimantan Se...
4           Lr. Kiaracondong No. 1Makassar, Sulbar 81715
...                                                  ...
29995      Jalan Soekarno Hatta No. 878Metro, Riau 01568
29996    Jl. HOS. Cokroaminoto No. 8Sorong, Sumbar 67464
29997   Jl. Abdul Muis  No. 540Subulussalam, Babel 60293
29998  Jl. Siliwangi No. 59Kota Administrasi Jakarta ...
29999  Jalan Suniaraja No. 9Kota Administrasi Jakarta...

                        created at
0      2018-07-08T13:31:43.241000Z
1      2018-07-27T07:19:43.924000Z
2      2018-03-19T20:19:02.226000Z
3      2018-03-23T10:14:13.225000Z
4      2018-12-11T09:31:02.254000Z
...                            ...
29995  2018-11-02T19:07:35.849000Z
29996  2018-11-26T19:04:48.343000Z
29997  2018-07-31T12:08:48.129000Z
29998  2018-11-16T06:34:56.477000Z
29999  2018-09-27T10:51:56.932000Z

[30000 rows x 5 columns]
      first name  last name                        email  \
0            Ian     Yuniar            kuswoyoedi@cv.com
1           Jaya  Wulandari       rkusmawati@hotmail.com
2       Cawisono  Sihombing   handayanikala@perum.sch.id
3          Rahmi    Maryati        bakdafarida@yahoo.com
4         Kamila      Usada            oskar85@perum.edu
...          ...        ...                          ...
29995    Tugiman   Prasasta          bnajmudin@pt.mil.id
29996       Tomi   Wibisono  dariminhutagalung@yahoo.com
29997    Tugiman   Najmudin        wfirmansyah@yahoo.com
29998      Bakti    Mustofa           gawati51@gmail.com
29999      Kezia     Wijaya              rsantoso@ud.org

                                                 address  \
0          Lr. Rajawali Timur No. 03Bitung, Sumbar 88384
1      Lr. Cihampelas No. 938Kota Administrasi Jakart...
2         Jl. Ir. H. Djuanda No. 894Medan, Kalteng 81006
3      Lr. Raya Setiabudhi No. 2Padang, Sumatera Utar...
4                   Lr. Sukajadi No. 88Langsa, DIY 82597
...                                                  ...
29995       Lr. Pasir Koja No. 0Surabaya, Bengkulu 46781
29996    Jl. Jend. Sudirman No. 6Langsa, Gorontalo 90376
29997  Lorong Pasir Koja No. 271Salatiga, Kalimantan ...
29998  Gg. Gedebage Selatan No. 99Palembang, Jawa Bar...
29999    Lorong Dr. Djunjunan No. 739Malang, Kepri 01549

                        created at
0      2018-10-06T14:48:33.186000Z
1      2018-07-08T02:44:52.822000Z
2      2018-07-10T01:35:35.033000Z
3      2018-02-13T22:37:18.392000Z
4      2018-06-10T23:44:40.214000Z
...                            ...
29995  2018-09-16T06:59:30.269000Z
29996  2018-08-03T21:29:45.610000Z
29997  2018-05-28T09:14:58.913000Z
29998  2018-09-18T10:56:04.491000Z
29999  2018-02-11T20:33:09.466000Z

[30000 rows x 5 columns]

In [31]:
def send_csv_to_psql(connection,csv,table_):
    sql = "COPY %s FROM STDIN WITH CSV HEADER DELIMITER AS ','"
    file = open(csv, "r")
    table = table_
    with connection.cursor() as cur:
        cur.execute("truncate " + table + ";")  #avoiding uploading duplicate data!
        cur.copy_expert(sql=sql % table, file=file)
        conn.commit()
#         cur.close()
#         conn.close()
    return conn.commit()

In [38]:
send_csv_to_psql(conn,'data-part-1.csv','user_address_master')
send_csv_to_psql(conn,'data-part-2.csv','user_address_master')
send_csv_to_psql(conn,'data-part-3.csv','user_address_master')
send_csv_to_psql(conn,'data-part-4.csv','user_address_master')
send_csv_to_psql(conn,'data-part-5.csv','user_address_master')
send_csv_to_psql(conn,'data-part-6.csv','user_address_master')
send_csv_to_psql(conn,'data-part-7.csv','user_address_master')
send_csv_to_psql(conn,'data-part-8.csv','user_address_master')
send_csv_to_psql(conn,'data-part-9.csv','user_address_master')
send_csv_to_psql(conn,'data-part-10.csv','user_address_master')